### ISSUE TITLE
Duplicate reactions not checked when adding reactions one-by-one

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1019]
**Problem description**

Duplicate reaction checks are only triggered when reactions are imported from file (see code below).

**Steps to reproduce**

```
gas = ct.Solution('h2o2.yaml')

gas1 = ct.Solution(thermo='IdealGas', kinetics='GasKinetics',
                   species=gas.species(), reactions=[])

yaml = """
    equation: H + O2 + H2O <=> HO2 + H2O
    rate-constant: {A: 1.126e+19, b: -0.76, Ea: 0.0}
    """
rxn = ct.Reaction.fromYaml(yaml, gas1)

gas1.add_reaction(rxn)
gas1.add_reaction(rxn) # <--- this is where error should be triggered

fname = 'duplicate.yaml'
gas1.write_yaml(fname) # use serialization from 2.6

gas2 = ct.Solution(fname) # <--- triggers error
```

*Edit: This example is longer than necessary, but it illustrates in what context this may come up.*

**System information**

- Cantera version: latest development 
- OS: Ubuntu

**Comment by speth** [comment]
Not checking duplicate reactions when adding them this way is deliberate, for two reasons.

First, you will get yourself into a catch-22 situation, since the rules specified for duplicate reactions are not only that duplicate reactions must be marked as such, but also that reactions which are not duplicates must not be marked as duplicate. So if you were to impose those rules, you wouldn't be able to add the first reaction of a pair of marked duplicates.

Second, the `Kinetics::checkDuplicates` function builds a couple of temporary data structures so that each reaction only needs to be checked against a handful of other reactions. Without this data structure, you'd have to check each reaction against each other reaction, which has O(N^2) behavior. Cantera used to do this, and it was a caused a noticeable slowdown when importing mechanisms with large numbers of reactions.

Neither of these are insurmountable problems, of course, but I figured the context for the current implementation would be useful.

**Comment by ischoegl** [comment]
Thanks for the insights. Certainly interesting, although the behavior is quite unexpected. Now that serialization is possible, it may be more of an issue. **PS:** having reaction factories may make this a little easier to address down the road.

**Comment by ischoegl** [comment]
Closing. This is redundant as any changes should be approached from Cantera/enhancements#132.
