### ISSUE TITLE
Sporadic failures of CI in test_mass_flow_controller

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1033]
**Problem description**

Recent CI runs show spurious failures of `test_reactor.TestIdealGasReactor.test_mass_flow_controller` in the Sundials suite. It appears that failures do not occur for every run: thus far, they most often occurred for Sundials 5.7, but at least one failure occurred for Sundials 3.

**Steps to reproduce**

E.g. see recent GH Actions failures in #1032

**Behavior**

Test fails with 
```
======================================================================
FAIL: test_mass_flow_controller (cantera.test.test_reactor.TestIdealGasReactor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cantera/cantera/build/python/cantera/test/test_reactor.py", line 478, in test_mass_flow_controller
    self.assertArrayNear(ma * Ya + 0.1 * gas2.Y, mb * Yb)
  File "/home/runner/work/cantera/cantera/build/python/cantera/test/utilities.py", line 82, in assertArrayNear
    self.fail(worst[1])
AssertionError: AssertNear: 0.1 - 0.10000000665769 = -6.6576915647154e-09
Relative error for element (0,) of 6.651040e-08 exceeds rtol = 1.000000e-08

----------------------------------------------------------------------
```

**System information**

- Cantera version: latest `main` (19f1593476112279d2d8045ba09f193038335bc1)
- OS: GH Actions

**Comment by speth** [comment]
I noticed this as well, and was trying to figure out whether there was any difference in the CI setup between the runs that succeed and those that fail. As far as I can tell, they're identical - same virtual environment image, and same versions of all the dependencies besides Sundials.

Running this test locally, I get a relative error of 8.8e-12 for this test, and 5.9e-12 for the related test for the `Reactor` class. I've added some debug information in #1035 see if it sheds any light on the problem.

**Comment by ischoegl** [comment]
It’s quite odd as it hasn’t happened with other runners thus far (just Sundials) and it is a very recent phenomenon (albeit pre #1025 merge). One simple/pragmatic solution would be to adjust tolerances, but I don’t like non-deterministic behavior … this may be a symptom of another issue after all

**Comment by speth** [comment]
While I think it's likely that this will end up with us either relaxing the test tolerances or tightening the integrator tolerance, I don't want to jump to that conclusion. It is interesting that this seems to actually be non-deterministic, rather than just attributable to some very specific combination of dependency versions, which are what we seem to find more often.

**Comment by speth** [comment]
I've tried two fixes for this, either of which seem to be sufficient to fix the problem.

* #1035 - Use the Sundials built-in linear solvers instead of OpenBLAS for these tests
* https://github.com/speth/cantera/pull/2 - Decrease `ReactorNet.rtol` to 1e-12 for this test.

I've forced the CI to run three times on each of these, to make sure that it was actually fixed.

I think I have a slight preference for the second solution, for the sake of keeping some tests around that use OpenBLAS, but I'd appreciate any other input.

As far as determining the origin of this failure, I did notice that this seems to correspond to an update to the Ubuntu 20.04 virtual environment in GitHub Actions. However, I don't see any changes that would obviously matter: https://github.com/actions/virtual-environments/commit/158ed05b6540b2ca90b3464246721e5050a8fb53#.

**Comment by bryanwweber** [comment]
The @conda-forge/cantera packages use OpenBLAS, so I'd suggest we keep some jobs around to test against OpenBLAS. It seems like the failures only ever occurred on Conda-based jobs; ~was there a recent update to the OpenBLAS package?~ The `openblas` package was updated 8 days ago (~May 3), which (if memory serves) seems to correspond to the start of these issues: https://anaconda.org/conda-forge/openblas/files

**Comment by speth** [comment]
Setting `OPENBLAS_NUM_THREADS=1` seems to also be a solution to this problem (https://github.com/speth/cantera/pull/4). Thanks to @bryanwweber for pointing out why my attempt to disable multithreading with `OMP_NUM_THREADS` didn't have any effect.

I think this is my preferred solution to the problem -- multithreading is a great way to run into nondeterministic behavior, and I don't think testing with it enabled will ever help us debug issues that are actually within our control.

**Comment by ischoegl** [comment]
🎉 … great that this mystery was solved - excellent work! It’s quite evident that setting the environment variable is a great solution for CI.

**Comment by speth** [comment]
Following the apparent failure of #1039 to reliably fix this, I explored a more significant change to this test. One thing to note about this test is that it's (deliberately) somewhat rough on the ODE solver. We are providing a mass flow rate function that's a square wave, so it has detect that it's not resolving something at the point where the square wave switches and (repeatedly) reduce the timestep.

In https://github.com/speth/cantera/pull/3, I modified this test to use a single triangular pulse, so that the imposed mass flow rate is at least continuous, if not smooth (we still want the ODE solver to have something to chew on). I've restarted the GH Actions for this 4 times and haven't seen a failure yet, so I think this may be a more reliable solution than getting into a fight with OpenBLAS.
