### ISSUE TITLE
Setting X on Solution object changes P unexpectedly

### ISSUE THREAD

**Issue by corykinney** [Cantera/cantera#1058]
**Problem description**

Setting the mole fractions on a Solution object, after previously initializing the temperature and pressure of the object, changes the pressure. Setting `TPX` directly doesn't cause any issues, but setting `TP` and then subsequently setting `X` results in this error. I can't think of a reason why this would be intentional, so it would seem to be either unintuitive or a critical bug.

**Steps to reproduce**
Minimum reproducible code sample:
```
import cantera as ct

gas = ct.Solution("gri30.yaml")
gas.TP = 1100, 1e7

print(f"TP = {gas.T:.0f} K, {gas.P:.0f} Pa")
gas.X = "O2: 1"
print(f"TP = {gas.T:.0f} K, {gas.P:.0f} Pa")
```

**Behavior**
Executing the above code gives the following output:
```
TP = 1100.0 K, 10000000 Pa
TP = 1100.0 K, 630039 Pa
```

**System information**

- Cantera version: 2.5.1
- OS: Windows 10
- Python version: 3.9.1

**Comment by bryanwweber** [comment]
Hi! Thanks for opening this issue. This behavior is intentional. The default state variables for an ideal gas in Cantera are temperature and density, not pressure. As such, temperature and mixture mass density are held constant when the composition changes. The `TPX` (likewise `TPY` and all the rest) setter is aware of this, so it sets the mole fractions first, then the temperature and pressure.

**Comment by corykinney** [comment]
@bryanwweber Thanks for the explanation! It occurred to me that perhaps there was a different state variable being held constant, but the behavior just seemed very unintuitive to me when I was initializing an object as with the seemingly innocuous `TP` and then `X` on a separate line and encountering strange results. I guess the takeaway is to always try to set the entire state in one setter call! Sorry for the unnecessary bug report.

**Comment by bryanwweber** [comment]
No problem! If I recall correctly, we explain this in some of our tutorials, and I try to mention it whenever I teach about Cantera, it's certainly weird the first time you see it. For what it's worth, I usually think of it as always setting the composition first, in case I don't want to use a three property setter. As one other note, the `set_equivalence_ratio()` function does hold pressure constant by design.
