### ISSUE TITLE
Cantera not throwing any error on the misuse of the attribute 'Q'

### ISSUE THREAD

**Issue by syedshayanz** [Cantera/cantera#1093]
**Problem description**

I used the command "air.HPQ = None, Pa, 'o2:0.21, n2:0.79, AR:0.01'" and it worked. When I checked the results, it appeared that cantera just ignores the Q attribute instead of indicating that a string cannot be assigned for Q.

**Steps to reproduce**

1. Run the following commands in cantera: 
import cantera as ct
gas = ct.Solution('gri30.yaml')
air = ct.Quantity(gas, constant='HP')
air.HPQ = None, None, 'o2:0.21, n2:0.79, AR:0.01'

2. Error should be seen since a string is being assigned to Q, but no error appears.

**Behavior**

Cantera just ignores the wrong assignment to Q, but instead it just runs while ignoring the misuse of Q.

**System information**

- Cantera version: 2.5.1
- OS: macOS 11.4 Big Sur
- Python/MATLAB/other software versions: Python 3.7.9

**Attachments**

**Additional context**
[cantera_issue.py.zip](https://github.com/Cantera/cantera/files/7139160/cantera_issue.py.zip)

**Comment by ischoegl** [comment]
Hi @syedshayanz - thanks for reporting this issue. The `Q` in this setter refers to _quality_ of a pure substance (`ct.Purefluid`, e.g. `ct.Water`), see https://github.com/Cantera/cantera/blob/cf085e47e4f23b966055350cfd6ff6ba02fb75ea/interfaces/cython/cantera/thermo.pyx#L1783-L1788

The property doesn't exist for `ct.Solution`, but somehow it appears to be added by `ct.Quantity` anyways.

**Comment by bryanwweber** [comment]
@ischoegl I also briefly looked at those files this afternoon and couldn't figure out how `HPQ` got added to `ct.Quantity`...

**Comment by ischoegl** [comment]
Same here. What’s somewhat troubling is that this would be a setter that does not exist even for `Purefluid`

**Comment by ischoegl** [comment]
@bryanwweber and @syedshayanz ... actually that behavior isn't too surprising after all. Python allows to attach a new attribute to any object, e.g. (building on the original code sample)
```python
>>> air.spam = None, None, 'o2:0.21, n2:0.79, AR:0.01'
>>> air.spam
(None, None, 'o2:0.21, n2:0.79, AR:0.01')
```
so I don't think that anything needs to be done here. In the example above, `spam` is a new attribute that has nothing to do with Cantera. Same would be true for `HPQ` - it just happens that it is defined for another related object?

**Comment by bryanwweber** [comment]
Ah, good point @ischoegl. I forgot about that. Given this is a Python feature, I agree there's probably not a lot to be done about it without a lot of other side effects. What do you think @syedshayanz?

**Comment by ischoegl** [comment]
Thanks @bryanwweber. While you posted this, I created this simple example:
```python
class Spam:
    foo = 3
    @property 
    def bar(self):
        return self.foo * 2
```
Now, using that you get
```python
>>> x = Spam()
>>> x.baz = 9
>>> x.foo, x.bar, x.baz
(3, 6, 9)
```
So the behavior is completely consistent with standard Python. I agree that we probably don't want to mess with a standard Python feature, so I'd suggest to close this issue.

**Comment by speth** [comment]
Thanks for the investigative work, @ischoegl and @bryanwweber. This threw me for a bit of a loop at first because a similar misuse of a `Solution` object does generate an error:
```python
>>> gas = ct.Solution('gri30.yaml')
>>> gas.HPQ = None
AttributeError: 'Solution' object has no attribute 'HPQ'
```
This is a result of the `Solution` class having a `__slots__` property that eliminates the `dict` used to store instance attributes.

We could do the same thing for the `Quantity` class, and I think doing so would make sense, since both classes rely so heavily on property setters, and it would nice to be able to catch typos or an incorrect assumption about a setter that is assumed to exist like the above example.

**Comment by ischoegl** [comment]
@speth ... thanks for this comment - I wasn't aware of `Solution` throwing an error for an equivalent _typo_, but what I summarized above sufficiently explains what was going on for `Quantity`. Since the latter inherits from the former, implementing the `__slots__` property may indeed make sense. I just haven't used it myself thus far ...
