### ISSUE TITLE
SDToolbox

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Cantera/cantera#120]
```
It would be nice if this 
(http://www2.galcit.caltech.edu/EDL/public/cantera/html/SD_Toolbox/) was  
integrated into a Cantera release
```

Original issue reported on code.google.com by `colin.he...@gmail.com` on 10 Oct 2012 at 6:20

**Comment by bryanwweber** [comment]
According to the maintainers of the SDToolbox, they have updated for Cantera 2.3 and 2.4, and will eventually be posting the code on GitHub. https://groups.google.com/d/msg/cantera-users/VKGf9Qo7Xeo/IeUjc6vJCgAJ

Since they still seem willing to maintain the toolbox, I don't think it needs to be integrated to Cantera. Closing this issue.
