### ISSUE TITLE
Yaml duplicate reaction issue

### ISSUE THREAD

**Issue by abimren** [Cantera/cantera#1278]
As I reported in 1092, some reactions are needed to be declared as duplicates in the latest stable release (2.6.0) to make mechanism work, though they are not.

Example reactions:
ELEMENTS
H O C N
END
SPECIES
CH3CO CH3 CO OH
END
REACTIONS
CH3CO + M = CH3 + CO + M 4.37E+15 0.0 10500.0
CH3CO + OH = CH3 + CO + OH 3.000E+13 0.0 0.
END

**Comment by ischoegl** [comment]
See #1251 - as of Cantera 2.6, both reactions are of the same type, and `OH` in the second version is just a special case of a third-body collider.

**Comment by abimren** [comment]
In the first reaction, M is total concentration.

Second one's third body is only OH.

If I declare DUP, is each reaction going to calculate a distinct third body? That's my confusion.

**Comment by ischoegl** [comment]
Looking at the source code, there is a check that ensures that collision efficiency definitions should be mutually exclusive. In this case, this check fails based on the way it is implemented. While the logic is unchanged from earlier versions, it now flags duplicates where there wasn't a conflict before as the reaction type was different.

The code section in question is https://github.com/Cantera/cantera/blob/2bc02637b1d6df0fb4203b70c4efafe14e0fb9fc/src/kinetics/Kinetics.cpp#L186-L198
The reason here is that the default efficiency for `M` is unity, and thus the check fails for `OH`.

The workaround is to declare DUP which will work as expected. As an aside, there is a discussion that goes beyond, see Cantera/enhancements#132.

**PS:** There's also this discussion #1193

**Comment by ischoegl** [comment]
Per discussion in #1193, the recommended resolution is to mark these reactions as duplicates. Please feel free to comment on Cantera/enhancements#132. Closing.
