### ISSUE TITLE
Incorrect CMake flags for C++ samples on Windows

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1375]
**Problem description**

Linker flags for the CMake build route of C++ samples are incorrect/insufficient on Windows systems.

**Steps to reproduce**

```
> scons build
> scons install
> cd path/to/samples/cxx/demo
```

Replace backslashes in `CMakeLists.txt` (see #1374)

```
> cmake .
```

The next step results in the following error (many instances of the LNK2038 error are removed for brevity):
```
 > cmake --build .
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Using triplet "x64-windows" from "C:\Users\ischo\GitHub\vcpkg\installed\x64-windows\"
cantera.lib(format.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '
2' in demo.obj [C:\Users\ischo\miniconda3\envs\cantera-dev\share\cantera\samples\cxx\demo\demo.vcxproj]
cantera.lib(format.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't matc
h value 'MDd_DynamicDebug' in demo.obj [C:\Users\ischo\miniconda3\envs\cantera-dev\share\cantera\samples\cxx\demo\demo.
vcxproj]
[...]
cantera.lib(CVodesIntegrator.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't mat
ch value '2' in demo.obj [C:\Users\ischo\miniconda3\envs\cantera-dev\share\cantera\samples\cxx\demo\demo.vcxproj]
cantera.lib(CVodesIntegrator.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' do
esn't match value 'MDd_DynamicDebug' in demo.obj [C:\Users\ischo\miniconda3\envs\cantera-dev\share\cantera\samples\cxx\
demo\demo.vcxproj]
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\Users\ischo
\miniconda3\envs\cantera-dev\share\cantera\samples\cxx\demo\demo.vcxproj]
C:\Users\ischo\miniconda3\envs\cantera-dev\share\cantera\samples\cxx\demo\Debug\demo.exe : fatal error LNK1319: 226 mis
matches detected [C:\Users\ischo\miniconda3\envs\cantera-dev\share\cantera\samples\cxx\demo\demo.vcxproj]
```

**System information**

- Cantera version: 3.0.0a2
- OS: Windows 10
- VS2022
- Installation in conda environment (including cmake)

**Comment by speth** [comment]
According to https://stackoverflow.com/questions/19024259/how-to-change-the-build-type-to-release-mode-in-cmake, doing a "release" build should be toggled as part of the build command:
```
cmake --build . --config Release
```
rather than being something that is baked into the `CMakeLists.txt` file. I tested this and it seems to work.

So I think this is basically a documentation issue. I'm not sure what the best place to add something would be -- perhaps https://cantera.org/tutorials/cxx-guide/compiling.html#cmake? Right now, this only provides an example of the  `CMakeLists.txt` file, but doesn't mention anything about how to run CMake and the native build system.
