### ISSUE TITLE
Floating point representations of valid integer geometry flags crash ck2yaml

### ISSUE THREAD

**Issue by corykinney** [Cantera/cantera#1395]
**Problem description**

`c2yaml` crashes when the transport geometry flag is a float representation of a valid integer flag (e.g. `0.000`, `1.000`, `2.000`). 

**Expected Behavior**

This has been discussed previously in #446, but rather than reviving that issue I decided to create a new one. The resolution in #454 was that the user is responsible for fixing floats instead of silently fixing the issue. Since the point of `ck2yaml` is to convert existing CHEMKIN mechanisms to a Cantera format, I would argue that float representations of valid integer flags should be automatically accepted as they are valid CHEMKIN inputs. Manually fixing the geometry flags for mechanisms such as AramcoMech 3.0 (as distributed by [NUIGalway](https://c3.universityofgalway.ie/combustionchemistrycentre/mechanismdownloads/)) with hundreds of species is unnecessarily tedious.

**Version**

Cantera 2.6.0a3

**Comment by bryanwweber** [comment]
Thanks here as well @cory-kinney! As you can see from my comment on the PR, I'm still pretty salty at CHEMKIN in general :smile: Specifically to the tedium point, I'd say that this would be a great place to write a quick utility script to reformat the file rather than doing it manually, until and if #1396 is merged and Cantera 3.0 is released with the changes.
