### ISSUE TITLE
Two solution objects have same T, P and mixing ratios, but compute slightly different production rates

### ISSUE THREAD

**Issue by Nicholaswogan** [Cantera/cantera#1410]
I'm using the Python interface to Cantera to compute reaction rates, which I then integrate forward in time using an integrator external to Cantera. I have encountered a situation where two Cantera Solution objects have the same T, P and mixing ratios, but compute slightly different reaction rates. Consider the following dummy code:

```python
T = 300
P = 1e5
X = np.array([.25,.25,.5])

gas1 = ct.Solution('mechanism_file.yaml')
gas2 = ct.Solution('mechanism_file.yaml')

def do_lots_of_stuff(gas):
    # Here I perform an integration using `gas` to compute reaction rates
    pass

do_lots_of_stuff(gas1)

gas1.TPX = T,P,X
gas2.TPX = T,P,X

print(gas1.T == gas2.T) # True
print(gas1.P == gas2.P) # True
print(np.all(gas1.X == gas2.X)) # True

rates1 = gas1.net_production_rates
rates2 = gas2.net_production_rates
print(np.all(rates1 == rates2)) # FALSE!
```

When i compute `np.abs(1-rates1/rates2)`, the largest values are about 1e-5, but most value are smaller (~1e-10). I would expect `rates1` and `rates2` to be identical, given the objects have the same T, P and mixing ratios. There must be something subtly different about the two objects `gas1` and `gas2` caused by `do_lots_of_stuff`.

I am unable to reproduce this problem with a minimal working example. I have tried very hard to make a simple version of `do_lots_of_stuff`, but have been unsuccessful. `do_lots_of_stuff` calls functions like `gas.mean_molecular_weight`, `gas.equilibrate('TP')`, and `gas.net_production_rates`.

**System information**

- Cantera version: 2.6.0
- OS: MacOS 11.6, M1 chip
- Python/MATLAB/other software versions: Python

**Comment by decaluwe** [comment]
Thanks, Nick—I really appreciate the thorough documentation of the problem. Question: if your print the differences between the rates (rather than 1 - rates1/rates2), what are the largest values?  If two rates are very very small, a ratio of 1+/- 1e-5 might not concern me too much (for example, if rate 1 = 1e-14, and rate2=1.00005e-14). Best,Steven Sent from my iPhoneOn Dec 1, 2022, at 11:41 AM, Nick Wogan ***@***.***> wrote:﻿
I'm using the Python interface to Cantera to compute reaction rates, which I then integrate forward in time using an integrator external to Cantera. I have encountered a situation where two Cantera Solution objects have the same T, P and mixing ratios, but compute slightly different reaction rates. Consider the following dummy code:
T = 300
P = 1e5
X = np.array([.25,.25,.5])

gas1 = ct.Solution('mechanism_file.yaml')
gas2 = ct.Solution('mechanism_file.yaml')

def do_lots_of_stuff(gas):
    # Here I perform an integration using `gas` to compute reaction rates
    pass

do_lots_of_stuff(gas1)

gas1.TPX = T,P,X
gas2.TPX = T,P,X

print(gas1.T == gas2.T) # True
print(gas1.P == gas2.P) # True
print(np.all(gas1.X == gas2.X)) # True

rates1 = gas1.net_production_rates
rates2 = gas2.net_production_rates
print(np.all(rates1 == rates2)) # FALSE!
When i compute np.abs(1-rates1/rates2), the largest values are about 1e-5, but most value are smaller (~1e-10). I would expect rates1 and rates2 to be identical, given the objects have the same T, P and mixing ratios. There must be something subtly different about the two objects gas1 and gas2 caused by do_lots_of_stuff.
I am unable to reproduce this problem with a minimal working example. I have tried very hard to make a simple version of do_lots_of_stuff, but have been unsuccessful. do_lots_of_stuff calls functions like gas.mean_molecular_weight, gas.equilibrate('TP'), and gas.net_production_rates.
System information

Cantera version: 2.6.0
OS: MacOS 11.6, M1 chip
Python/MATLAB/other software versions: Python

**Comment by Nicholaswogan** [comment]
@decaluwe, the differences between the rates are small like you describe (e.g. rate1 = 1e-14 and rate2=1.00005e-14). The effect has a negligible effect on my calculation overall

**Comment by ischoegl** [comment]
> I am unable to reproduce this problem with a minimal working example. I have tried very hard to make a simple version of `do_lots_of_stuff`, but have been unsuccessful. `do_lots_of_stuff` calls functions like `gas.mean_molecular_weight`, `gas.equilibrate('TP')`, and `gas.net_production_rates`.

> […] the differences between the rates are small like you describe (e.g. rate1 = 1e-14 and rate2=1.00005e-14).  The effect has a negligible effect on my calculation overall

Exact comparison of floating point values is often difficult, where usual practices recommend bracketing with a combination of absolute and relative tolerances instead. In this case, my suspicion is that internal tolerance checks assess the states as equivalent, so values in question are not being recalculated and buffered values are used instead. Without a reproducible example, I believe that the issue should be closed.
