### ISSUE TITLE
Duplicate initial gas property in python example ic_engine.py

### ISSUE THREAD

**Issue by flight-test-engineering** [Cantera/cantera#1460]
Gas properties are defined 2 times in [ic_engine.py](https://cantera.org/examples/python/reactors/ic_engine.py.html)

This is just a documentation issue.

Line `gas.TPX = T_inlet, p_inlet, comp_inlet` is duplicated:

```
...
#####################################################################
# Set up Reactor Network
#####################################################################

# load reaction mechanism
gas = ct.Solution(reaction_mechanism, phase_name)

# define initial state and set up reactor
gas.TPX = T_inlet, p_inlet, comp_inlet
cyl = ct.IdealGasReactor(gas)
cyl.volume = V_oT

# define inlet state
gas.TPX = T_inlet, p_inlet, comp_inlet
inlet = ct.Reservoir(gas)
...
```

Suggest to remove duplicate.

**Comment by bryanwweber** [comment]
Thanks for reporting this! Despite appearances, I believe this is intended. The reason is that in principle, the reservoir can have a different state than the reactor (cylinder). As such, we are demonstrating that you can set those values before creating the reservoir, even on the same object, without changing the reactor.

However, a note to that effect is probably warranted! Thanks ☺️

**Comment by flight-test-engineering** [comment]
Thanks for responding. Yes, it makes sense. Should I close the issue?

**Comment by bryanwweber** [comment]
No, I think we can leave it open, with the fix being a comment describing what's going on. If you'd like to open a pull request with the change, please feel free!
