### ISSUE TITLE
Failed to run cantera on virtual machine

### ISSUE THREAD

**Issue by a850819689** [Cantera/cantera#1480]
**Problem description**

<Windows10 operating system, python environment using pip installation to run cantera file error reporting>

**Steps to reproduce**

1. Open the cmd command line, run ' py-m pip install cantera ' and prompt ' Successfully installed cantera-2.6.0.post1 '.
2. Running test example ‘py -m cantera.examples.thermo.critical_properties’
3. See error 
   'Traceback (most recent call last):
    File "D:\python\lib\runpy.py", line 185, in _run_module_as_main
       mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
    File "D:\python\lib\runpy.py", line 111, in _get_module_details
       __import__(pkg_name)
    File "C:\~\ct-env\lib\site-packages\cantera\__init__.py", line 4, in <module>
       from ._cantera import *
   ImportError: DLL load failed while importing _cantera: The specified module could not be found‘

**Behavior**

When I use my personal computer to do the above operation, there is no error and the canter file can run normally.
I 've tried to reinstall cantera and python many times but still get errors.

**System information**

- Cantera version: 2.6.0
- OS: Windows 10
- Python

**Comment by bryanwweber** [comment]
Hi, thanks for reporting this! The path to the example file does not match the path to Python. The example file starts with `C` instead of `D`. The ~ also looks strange to me. Do you have an old installation of Cantera somewhere on the C drive? Perhaps from anaconda? How did you create the file system for the VM? 

Actually, that path is even stranger. There should not be a file called `cantera_init.py` anywhere in `site-packages`. Where did that file come from?

**Comment by a850819689** [comment]
Thank you very much for your reply! After my investigation, it should be that cantera is not compatible with the python version I currently use.I reinstalled version 3.7.6 of python and the problem was solved.

**Comment by bryanwweber** [comment]
Great, thank you! I'll close this issue as solved then.
