### ISSUE TITLE
NotImplementedError thrown by ThermoPhase::satPressure:

### ISSUE THREAD

**Issue by pjohn71** [Cantera/cantera#1646]
**Problem description**
Calling cantera.Solution.P_sat throws NotImplementedError thrown by ThermoPhase::satPressure:

I might not be calling the P_sat property very well. I will be glad if I can be directed on how to used the P_sat property from the Solution Class in cantera

**Steps to reproduce**
Run the code below:

import cantera as ct
fuel_obj = ct.Solution("gri30.yaml")
fuel_obj.TPX = 300, 101325, 'CH4:1.0'
print(fuel_obj.P_sat)

**Behavior**
I got the following error
File cantera/thermo.pyx:1392, in cantera._cantera.ThermoPhase.P_sat.__get__()

CanteraError: 
*******************************************************************************
NotImplementedError thrown by ThermoPhase::satPressure:
Not implemented.
*******************************************************************************

**System information**

- Cantera version:  2.6.0 
- OS: [Windows 11]
- Python: 3.10

**Attachments**

**Additional context**

**Comment by bryanwweber** [comment]
Hi, this is because gri30.yaml is an ideal gas phase, which doesn't have a saturation pressure by definition. Currently in Cantera, you can create https://cantera.org/documentation/docs-3.0/sphinx/html/cython/importing.html#pure-fluid-phases that support the saturation pressure. 

If you want to provide more details about your use case and ask further questions, can you please post on the Users' Group https://groups.google.com/g/cantera-users since this is not an issue with Cantera itself? Thanks 😄

**Comment by pjohn71** [comment]
I have posted the question on the google groups
