### ISSUE TITLE
Update documentation for ck2cti

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#295]
It seems like the most complete documentation for how to use ck2cti is in the Matlab interface documentation: http://www.cantera.org/docs/sphinx/html/matlab/input-tutorial.html?highlight=ck2cti#converting-ck-format-files and even that seems out of date. We should update this documentation and describe the options, and perhaps also provide a short tutorial of use.

It _may_ be useful also to provide a short list of tips and tricks to get LLNL mechanisms to convert.

**Comment by speth** [comment]
The Matlab documentation for ck2cti is definitely out of date. The help provided by just running `ck2cti.py` is perhaps a bit terse, but it's at least complete.  It's also mentioned in the [Python tutorial](http://www.cantera.org/docs/sphinx/html/cython/tutorial.html#working-with-mechanism-files). Maybe it would be worth adding a section about ck2cti to the CTI guide (`doc/sphinx/cti/input-files.rst`) as well.

On the issue of the LLNL mechanisms, I was at one point working on a list of issues to send to the people there to see if we could get them fixed upstream, but since then they appear to have updated the mechanisms and added some different bugs (like the truncated transport database that's shown up on the mailing list a couple of times).
