### ISSUE TITLE
[Cython, at least] Setting up a ct.Mixture with one phase being ct.Water does not preserve quality

### ISSUE THREAD

**Issue by thomasfiala** [Cantera/cantera#306]
When I try to set up a Mixture with one phase being water with a certain quality between 0 and 1, this value is not preserved:

```
import cantera as ct
water = ct.Water()
air = ct.Solution('h2o2.xml')

water.TX = 380, 0.5
print(water.X)  # correctly is 0.5
air.TPX = 380, water.P, 'AR:1'

mix = ct.Mixture([(water, 100.), (air, 1.)])

print(water.X)  # should also be 0.5, but is 1.0
```

I can set a certain quality later on by `water.TX = 380, 0.5`.

**Comment by bryanwweber** [comment]
I suspect this is because [`updatePhases()`](https://github.com/Cantera/cantera/blob/master/src/equil/MultiPhase.cpp#L915) which is [called by the initializer](https://github.com/Cantera/cantera/blob/master/src/equil/MultiPhase.cpp#L213) of the Mixture class uses the `setState_TPX` method to set the state of each of the phases. Of course, for the PureFluid phases, the value of `X` has a different meaning than for most of the other phases (i.e. the quality vs. mole fraction). Since `setState_TPX` isn't overloaded in the PureFluid classes, it tries to set the temperature and pressure to the values of the Mixture and uses some value for the mole fractions that isn't relevant to the PureFluid.

Based on this, I also guess that it will apply to all the interfaces.

**Comment by speth** [comment]
I'm not sure that putting a `PureFluidPhase` in a `Mixture` is a very good idea in the first place. The `PureFluidPhase` is already multiphase mixture crammed into a single `ThermoPhase` object, and this doesn't work very well with `Mixture`'s idea that it is in charge of deciding how many moles of each substance are in which phase. , In order to interface with `Mixture`, I think you would want a phase to represent just liquid water and a phase to represent just water vapor, but that seems a bit weird when you have a single equation of state which actually covers both.

**Comment by thomasfiala** [comment]
Yes, this probably isn't a good idea. Apparently, the `equilibrate` function does not work correctly (probably because of the issue mentioned in #307 .

For example, the following code returns completely off results, but no error or warning:

```
import cantera as ct
water = ct.Water()
air = ct.Solution('h2o2.xml')
water.TX = 380, 0.5
print(water.X)  # correctly is 0.5
air.TPX = 380, water.P, 'H2O:1'
mix = ct.Mixture([(water, 100.), (air, 1.)])
water.TX = 380, 0.5
air.TPX = 380, water.P, 'H2O:1'
print(mix())
mix.equilibrate('HP')
print(mix())
```

**Comment by speth** [comment]
Well, to be fair, that method of changing the properties of the `Mixture` object doesn't work for any phase type, since the `Mixture` is defined by the state of the phases when it's created. Changing them later has no effect. For example:

``` python
import cantera as ct
gas = ct.Solution('h2o2.xml')
gas.TPX = 400, 2e6, 'H2:0.1, O2:0.9'
m = ct.Mixture([(gas, 1.0)])
gas.TPX = None, None, 'H2:1.0'
m.equilibrate('TP')
print(m())
```

This is similar to the way that `ThermoPhase` objects are used when initializing Reactor objects, where the initial state is all that matters, and later changes are necessarily ignored. This is part of what allows the same `ThermoPhase` objects to be used in multiple container objects.

**Comment by thomasfiala** [comment]
OK, that makes sense.
I guess it would then also be helpful to include a function like `update_phases` in `Mixture.report()`.
