### ISSUE TITLE
Setting TPX of a PureFluid results in an error (but should probably be undefined)

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#307]
There is no reason for a PureFluid to be able to set the temperature, pressure, and X (where X for a PureFluid is the vapor quality, not the mole fractions). Example:

```
>> import cantera as ct
>> w = ct.Water()
>> w.TX = 380, 0.5
>> w()

   water:

        temperature             380  K
           pressure          128618  Pa
            density         1.49268  kg/m^3
   mean mol. weight          18.016  amu
     vapor fraction             0.5

>> w.TPX = 373.15, 101325, 0.5
>> w.TPX = 373.15, 101325, 0.5
   ---------------------------------------------------------------------------
   ValueError                                Traceback (most recent call last)
   <ipython-input-22-8a529abadb62> in <module>()
   ----> 1 w.TPX = 373.15, 101325, 0.5

   interfaces/cython/cantera/thermo.pyx in cantera._cantera.ThermoPhase.TPX.__set__ (interfaces/cython/cantera/_cantera.cpp:20706)()

   interfaces/cython/cantera/thermo.pyx in cantera._cantera.PureFluid.X.__set__ (interfaces/cython/cantera/_cantera.cpp:26306)()

   ValueError: Cannot set vapor quality outside thetwo-phase region
```

The error comes out because the generic `TPX` function sets the `X` of the phase (thinking it should be the mole fractions) first, then tries to set the temperature and pressure. It works the first time, because the quality is set first, and then the state is overridden by the given temperature and pressure. Then the second time around it tries to set the quality, but can't because its outside the two-phase region.

Since T and P are not independent if X is specified, it should probably be undefined to set all three at the same time. This is also related to #306.

**Comment by speth** [comment]
The case where it doesn't raise an exception is definitely wrong.

I don't think it's possible to undefine the methods, since `PureFluid` inherits these methods from `ThermoPhase`. They can be overridden, either to throw an exception, or just defined to be `None`.

#306 is actually somewhat different -- overloading "X" to be both quality and mole fraction is only done in the Python interface.

**Comment by bryanwweber** [comment]
I think probably throwing a ValueError (or CanteraError? Can we throw those from the Python interface?) would be the best solution, something like

```
Cannot set the temperature, pressure, and vapor fraction simultaneously
```

To resolve this overloading, should we change the Python interface then, to use something like `q` for the quality?

I think its related to #306 in that `setState_TPX` should probably also be "undefined" (or defined to throw an error) for a `PureFluid` in the C++ level, so that the `Mixture::init()` method doesn't cause unexpected behavior, as described in that issue.

**Comment by speth** [comment]
The only overloading that exists in the Python case is for the property `X` alone. What I don't like about throwing the exception is that it takes the Python class `PureFluid`, which currently only has to implement three methods, and adds on 7 more that exist just to throw exceptions.

Changing the variable name would require first deprecating the existing methods, and it's still kind of dangerous because in the end you will still have the `X` property representing mole fractions, so it's not like the case where we just remove old functions.

On the C++ side, the issue is different. `setState_TPX` is still setting mole fractions, which is exactly what `Mixture` is trying to do. It's just for a phase that only has one species, so it's a no-op. The problem with `Mixture` is that it thinks that temperature and pressure are sufficient to describe the thermodynamic state, which isn't true for `PureFluidPhase`. But if you don't allow it to work that way, then all of the multiphase equilibrium algorithms, at least as currently implemented, can no longer be used.
