### ISSUE TITLE
gcc: error: unrecognized command line option '-Wl'

### ISSUE THREAD

**Issue by sagitter** [Cantera/cantera#320]
Hi again,

another issue that I do not know how to manage: `gcc` compiler does not recognize all `-Wl`options.

`-Wp`, for example, is an option that I use often with `gcc`/`g++` compilers, `-Wl,-z,relro` or `-Wl,-z,now` with the linker; why are they not permitted on Cantera?

Thanks.

**Comment by speth** [comment]
The problem is that the Cantera SConstruct file thinks that commas are delimiters between different options, e.g. if you write `scons build cxx_flags=-g,-O2` it would understand to call gcc with the `-g` and `-O2` options. But of course this doesn't work well with the use of commas for the exact same purpose within the `-Wl` option. 

As a workaround, you can specify this option in `cantera.conf` as a list explicitly, i.e.

``` python
cxx_flags = ['-g', '-Wl,-z,relro', '-Wl,-z,now']
```

And of course the same applies for the other options for setting compiler/linker options.

**Comment by sagitter** [comment]
Thank you for reply.

Do options set in `cantera.conf` overwrite those ones set with `scons` command?

**Comment by speth** [comment]
It works the other way around: if you do not specify a value in the `scons build` command line, it will use one from `cantera.conf`. If you _do_ specify a value to `scons build`, then that will be used to populate `cantera.conf`.

**Comment by speth** [comment]
Although there is a workaround, I think it might be preferable to modify the parsing of these compiler options (currently handled by the `listify` function in `buildutils.py`) so that flags like this can be passed in from the command line. Options for changing this are:
- Only allow spaces to be delimiters, which means that multiple values will need to be passed as quoted strings, e.g. `scons build cxx_flags="-g -O2"`
- Allow commas to be escaped in options like those above, e.g. `scons build cxx_flags=-O2,-Wl\\,-z\\,relro`.
  The second option has the advantage of not invalidating the currently-supported syntax, but double escaping required for the backslashes is kind of annoying.
