### ISSUE TITLE
Many "unused parameter" warnings

### ISSUE THREAD

**Issue by g3bk47** [Cantera/cantera#365]
Code like [THIS](https://github.com/Cantera/cantera/blob/2b2f733bd9d7f3957bb0e3ab27c4bd07a1b03053/include/cantera/thermo/ThermoPhase.h#L477) generates many "unused parameter" warnings when I try to compile my own programs. This messes up any "treat warnings as errors" setup.  I understand that you want to refer to the function argument by name in the doxygen text, but maybe omitting the argument name for the sake of warning-free code is more important? Maybe a better solution is moving the definition out of the header into the source file? Alternatively you could comment the argument name like this
`virtual void getChemPotentials_RT(doublereal* /*mu*/) const {`
but moving the definition into the source file seems more reasonable.

This also happens in a few other headers like `oneD/Domain1D.h`, `numerics/GeneralMatrix.h` or `thermo/SpeciesThermoInterpType.h` where `NotImplementedError` is used.

**Comment by speth** [comment]
What compiler and flags are you using? Cantera compiles (mostly) warning-free on GCC, Clang, and MSVC using the `-Wall` or `/W3` flags. I guess maybe you're compiling with `-Wextra`? I think this highlights the fact that the 'unused parameter' warnings are prone to being false positives in just about any code that uses virtual methods. I don't think I have any desire to make Cantera compile with no warnings at the level of `-Wextra`.

I definitely don't like the idea of removing the parameter name in order to suppress the warning, even (or especially) in the absence of Doxygen documentation for the parameters.

Moving the definition to the source file is a possibility, but just adds unnecessary boilerplate for all of the unimplemented base class methods.

An alternative is that you could specify the Cantera include directory using `-isystem` instead of `-I`, which will suppress warnings for files in that directory but allow you to use whatever warning flags you like for your code.

**Comment by g3bk47** [comment]
The warnings are produced by Clang using -Wextra which enables -Wunused-parameter.

**Comment by speth** [comment]
I suggest that you either add `-Wno-unused-parameter` to your compiler flags, or use `-isystem` when adding the Cantera include directory to your search path.

Even the people who write the compiler don't think compiling with unused parameter warnings is worthwhile: https://llvm.org/bugs/show_bug.cgi?id=786
