### ISSUE TITLE
Appveyor builds that have test failures don't fail the build

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#382]
This build shows as successfully completing, despite 6 errors in the Python test suite: https://ci.appveyor.com/project/Cantera/cantera/build/1.0.51

Appveyor is being a real pain, dealing with false positives (the pip problem) and false negatives (this problem...)

By the way, in looking at that log, there seems to be another error related to pip that didn't cause the build to fail, which is that the upgrade process for pip for pip fails because a directory is not writable. Also, apparently the `--egg` option is deprecated.

**Comment by speth** [comment]
I don't think there's anything that can be done about the `--egg` deprecation for the time being. Without that option, installing SCons fails. If they actually remove it, then we'll have to resort to installing SCons from a release `.tar.gz`. Or we could modify the build to use an Anaconda environment instead.

I'm not quite sure why it claims "success" after the tests fail. Maybe it's because the last command in the `test_script` (uploading some test results) is succeeding? It might behave correctly if we can stash the return code of the `scons test` command and then exit the script with that value.
