### ISSUE TITLE
ck2cti documentation should be converted to Sphinx-style docstrings

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#397]
The documentation in the ck2cti.py script is currently in a custom format that doesn't seem to be read by the Sphinx docs (at least, I couldn't find a page for it). If the docstrings were rewritten to the standard format, the docs could be included online.

**Comment by speth** [comment]
I think the reason these are not in the Sphinx docs is not the format of the docstrings (they look like RST to me), but because there is no .rst file in the `doc` folder that asks for the documentation for these classes/functions, along the lines of `sphinx/cti/classes.rst`.

That said, would this really be useful to have in the Sphinx docs? Everything in `ck2cti.py` is just internal functions that are only useful within that script, with the exception of `convertMech` which has no docstring.

**Comment by bryanwweber** [comment]
Yeah, I think the format is RST but they don't, for instance, have `:param:` to describe the arguments, etc.

I guess including ck2cti in the docs could be confusing, because it has its own notion of what are a `Species` and `Reaction` etc. that are different from the definitions that are used in `ThermoPhase`. I still think it could be useful to have the docs online for anyone who wants to add to/change ck2cti, or perhaps see what might be going wrong in a conversion (although the error messages are generally very good). Just a thought, if it won't be worthwhile, this can be closed.

**Comment by speth** [comment]
Presumably the documentation page for these can provide clarity on what these classes are and avoid mixing them together with the Python module documentation.

I'm not sure how much help this would provide in debugging a failed conversion, but they can be useful to someone who wants to repurpose these classes, e.g. in the case of the tool for generating CTI files from existing `Solution` objects.

**Comment by bryanwweber** [comment]
@parkerclayton @kyleniemeyer Note that in ck2cti you can see the inverse of what you're trying, as @speth mentioned here.

**Comment by bryanwweber** [comment]
This is probably no longer necessary and time shouldn't be spent here, considering the impending removal of CTI in favor of YAML.
