### ISSUE TITLE
Creating a Solution from a CTI string throws an error because the argument is too long on Windows

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#416]
### Cantera version
2.3.0b1
### Operating System
Windows 10/Windows 7
### Python/MATLAB version
3.5.2
### Expected Behavior
A `Solution` is instantiated
### Actual Behavior
An error message is thrown by `ctml_writer`, the relevant part of which is
```
The filename or extension is too long.
[code 0x00ce (206)]
```
### Steps to reproduce
```
import cantera as ct
with open('species.txt', 'r') as cti_file:
    cti_source = cti_file.read()
ct.Solution(source=cti_source)
```
with the attached `species.txt`
[species.txt](https://github.com/Cantera/cantera/files/671344/species.txt)

**Comment by bryanwweber** [comment]
For what its worth, I don't get this error on OS X (haven't tested Linux, but I think its probably Windows specific).

**Comment by santoshshanbhogue** [comment]
If I execute `len(cti_source)`, I get:
251465 on a Win 10 OS
257507 on a Mac OS X

Perhaps something in the file itself is tripping the parser...?

**Comment by bryanwweber** [comment]
I think it has to do with how the converter is run from C++. Windows has some arcane limits on lengths of command lines, from its DOS heritage (IIRC), that *nix systems don't have. Interesting that the lengths are different though, and the Windows is shorter...

**Comment by skyreflectedinmirrors** [comment]
Bryan, is it possible that you're running into some variation of the [maximum path length](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath) limitation on Windows (260 chars)?  I know I have run into that before

That's what the error message suggests to me anyways

**Comment by santoshshanbhogue** [comment]
I think this is a cross-platform issue. I just tried converting a very large mechansism for methyl-butonate ester and get the same error on OSX as well...
`interfaces/cython/cantera/base.pyx in cantera._cantera._SolutionBase.__cinit__ (interfaces/cython/cantera/_cantera.cpp:7640)()

interfaces/cython/cantera/base.pyx in cantera._cantera._SolutionBase._init_cti_xml (interfaces/cython/cantera/_cantera.cpp:8057)()

CanteraError: 
***********************************************************************
CanteraError thrown by ct2ctml_string:
Error executing python while converting input file:
Python command was: '/Users/santosh1/anaconda/bin/python'
exec_stream_t::start: error in child process.exec_stream_t::start: exec in child process failed. /Users/santosh1/anaconda/bin/python
Argument list too long
[code 0x0007 (7)]
***********************************************************************`

**Comment by bryanwweber** [comment]
@arghdos Thanks for the link. Given the tests by @santoshshanbhogue it might be something that's just going to fail (I guess the limit is higher for *nix systems).

**Comment by santoshshanbhogue** [comment]
Just that for windows the error occurs for a smaller file size

**Comment by santoshshanbhogue** [comment]
The problem is this chunk of code in ct2ctml.cpp (line number 113):

`
        args.push_back(
                    "from __future__ import print_function\n"
                    "import sys\n"
                    "try:\n"
                    "    from cantera import ctml_writer\n"
                    "except ImportError:\n"
                    "    print('sys.path: ' + repr(sys.path) + '\\n', file=sys.stderr)\n"
                    "    raise\n"
                    "ctml_writer.convert(" + arg + ", outName='STDOUT')\n"
                    "sys.exit(0)\n");
`
As @bryanwweber mentions, this is just a matter of when the command will fail, because most operating systems have limits on the size of arguments passed via the command line.

I tried executing the same code above within a python shell and it runs just fine for the very large mechanisms on both Windows and MacOS. 

Perhaps we should raise an error if the text passed via `source=` exceeds 80,000 characters...? I say 80,000 because GRI3.0 is about 80,000 and it works just fine. The error can inform the user to use the file mode. PR worthy?

**Comment by speth** [comment]
Rather than imposing an arbitrary limit on the length of the `source` argument, wouldn't it be better if we wrote the input to a temporary file in the case where it is too long for the OS to handle on the command line? From a bit of testing, the limit seems to be about 128k characters on Linux and 64k characters on Windows. If OS X has a limit that is higher still, using 64k as the threshold ought to be fine.

**Comment by santoshshanbhogue** [comment]
Started a PR to deal with this (#417). Since this error occurs only for an abnormally large mechanism, it  is very likely that the user is reading from a file and then passing it as a source. So the error informs the user to pass the file itself. Much simpler than creating a temp file, etc -- I think

**Comment by bryanwweber** [comment]
I'm still having this issue on OpenSUSE Leap 42.2. I added some code to print out the various sizes of the mechanism I'm using
```
text.size(): 1497458
max_argv_size: 2097152
Size of argument string: 1497707
```
Given that `text.size()` (and, more saliently, the size of the argument string) is much less (~500k) than `max_argv`, I'm not really sure why I get this error. For simplicity in fixing this, I'm inclined to put a cap on the length at 32k for all operating systems. The only downside to capping at a relatively small number is that it will result in temp files being written to the disk, which this code was intended to avoid in the first place.

The other option would be to try to do the conversion and write to a temp file if it fails. This would require parsing the error message, but shouldn't be too hard. Can anyone offer some advice here?
