### ISSUE TITLE
MATLAB toolbox not working with SUNDIALS 2.7.0_2

### ISSUE THREAD

**Issue by gpavanb-old** [Cantera/cantera#431]
### Cantera version
2.3.0

### Operating System
Mac OS X

### Python/MATLAB version
2.7
MATLAB R2014b

### Expected Behavior
MATLAB toolbox invoked

### Actual Behavior
Invalid MEX-file '/Users/gpavanb/Cantera/lib/cantera/matlab/toolbox/ctmethods.mexmaci64':
dlopen(/Users/gpavanb/Cantera/lib/cantera/matlab/toolbox/ctmethods.mexmaci64, 6): Symbol not found: _CVLapackBand
  Referenced from: /Users/gpavanb/Cantera/lib/cantera/matlab/toolbox/ctmethods.mexmaci64
  Expected in: /Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.2.dylib
 in /Users/gpavanb/Cantera/lib/cantera/matlab/toolbox/ctmethods.mexmaci64

Error in adddir (line 11)
ctmethods(0, 3, d);

### Steps to reproduce
1. Install Cantera 2.3.0 with latest Sundials 2.7.0_2
2. Enable MATLAB toolbox. Using scons to build and install
3. Error on invoking any Cantera statement, e.g. gas = Solution('gri30.cti','gas')

**Comment by bryanwweber** [comment]
Unfortunately, this is a well known issue with Matlab on all platforms. Since Matlab includes its own shared libraries for SUNDIALS, we usually recommend that users don't link to SUNDIALS when they use the Matlab toolbox. In fact, the [official installation instructions](http://cantera.org/docs/sphinx/html/install.html#homebrew) for Homebrew on OS X explicitly state that SUNDIALS inclusion is turned off when building the Matlab interface (see item 3 on that list). Do you need SUNDIALS support for a particular use case?

**Comment by speth** [comment]
I guess we should disable linking to an external SUNDIALS library when compilation of the Matlab toolbox is enabled, the same way we do for the external BLAS/LAPACK libraries.
