### ISSUE TITLE
setup_cantera is not compatible with C shell

### ISSUE THREAD

**Issue by gpavanb-old** [Cantera/cantera#453]
### Cantera version
2.3.0

### Operating System
Linux

### Python/MATLAB version
2.7.13

### Expected Behavior
`source setup_cantera` should go smoothly without any prompts

### Actual Behavior
LD_LIBRARY_PATH: Undefined variable.
Exit 1

### Steps to reproduce
1. Install Cantera
2. source /path/to/setup_cantera

This is because you use the export command and it should switch to setenv based on the shell which is being used.

**Comment by bryanwweber** [comment]
I'm not totally sure what to do here... If we want to add runtime-support for other shells, on the one hand, adding this support should be relatively simple in principle by constructing a `case` statement (or `if-elif-else`) to check the shell version/type. On the other, how many shells should we support? Next thing will be `fish`, then `zsh`, then... all of them with different syntaxes.

Another option is to determine this at build time and output the correct shell script, but how would that be handled in the packaging infrastructure? This has the advantage that the complexity is hidden from the user, but we can't know what shell the downstream user is using and the user can change their shell at any time (which is why my first thought was runtime support).

I'm ambivalent on the options here.
