### ISSUE TITLE
fatal error: 'cvodes/cvodes_lapack.h' file not found

### ISSUE THREAD

**Issue by ryandesign** [Cantera/cantera#492]
### Cantera version

2.3.0

### Operating System

macOS 10.12.6

### Python/MATLAB version

Python 2.7.14 / no MATLAB

### Expected Behavior

Successful build

### Actual Behavior

```
src/numerics/CVodesIntegrator.cpp:18:14: fatal error: 'cvodes/cvodes_lapack.h' file not found
    #include "cvodes/cvodes_lapack.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### Steps to reproduce

I've tried installing sundials 2.7.0 with Apple's Accelerate framework (`-DBLA_VENDOR=Apple`) and also with OpenBLAS 0.2.20 (`-DBLA_VENDOR=OpenBLAS`). Either way, `#define SUNDIALS_BLAS_LAPACK` is present in $PREFIX/include/sundials/sundials_config.h but $PREFIX/include/cvodes/cvodes_lapack.h does not exist. I have not yet tried to compile sundials with ATLAS because ATLAS takes hours to build.

**Comment by speth** [comment]
It seems like you haven't gotten Sundials to build with LAPACK support -- otherwise, that header file would be present. What does the output of the CMake configuration say about it's tests for LAPACK?

If you don't want to compile Sundials separately with LAPACK support, you can take the easy route and let Cantera compile its own copy of the CVodes solver by setting `system_sundials=n` on the `scons build ...` command line.

I'm not seeing how this is a bug in Cantera; general help with compiling Cantera is probably better addressed on the Users' Group, and I would suggest moving this topic there if you want to follow up.

**Comment by ryandesign** [comment]
Sorry about that. You're right, sundials2 cmake output shows it is not finding blas/lapack. I've [filed a bug report](https://trac.macports.org/ticket/55553) about the MacPorts sundials2 port to get that fixed.
