### ISSUE TITLE
SolutionArray save / load 

### ISSUE THREAD

**Issue by rddaz2013** [Cantera/cantera#543]
Is there a way to save/load the SolutionArray.object

```
import pickle
# mal schauen ob der zwischenstand gesichert werden kann
pickle.dump( states, open( "save.p", "wb" ) )
```

doesn't work.... I want to save my Solution within the SolutionArray.object and load the data in a other python source. Yes i can save it in CSV but then the nice functions of SolutionArray.object is missing.

Is there a way to save multipy scenarios on disk an reuse them later?

**Comment by speth** [comment]
No, there is no way to pickle a `SolutionArray` because the underlying C++ objects which make up the `Solution` object cannot be pickled.

The less complicated approach would be to add a `load_csv` method to the `SolutionArray` class, which would essentially be the inverse of the `write_csv` method, and I think that would be a useful feature addition.

**Comment by rddaz2013** [comment]
I Look into it.

Ray Speth <notifications@github.com> schrieb am Mi., 13. Juni 2018 um
18:06 Uhr:

**Comment by rddaz2013** [comment]
C++ objects? mhh I think the dynamic use of__setattr__ within makes it hard for pickle to do the job.

**Comment by ischoegl** [comment]
#679 and #680 seek to add HDF output via pandas. Implementing the reverse is straightforward, which may be a way to introduce this missing feature. If set up properly, CSV import can use almost identical machinery.
