### ISSUE TITLE
MassFlowController is not extracting mass properly

### ISSUE THREAD

**Issue by Repiklis** [Cantera/cantera#551]
### Steps to reproduce
The code below excibits the above behaviour. It includes a Hydrogen reactor with a MassFlowController. The mass flow stays closed until the DormTime and is switched off an hour later. I used 1 sec as my dt, since it seems to be more stable. 

    import cantera as ct
    
    #Variables
    DormTime = 0.3 #hrs
    TotTime = 1.5 #hrs
    
    #Tank Reactor
    LH2 = ct.Hydrogen()
    LH2.TD = 20.24, 44.623
    
    LR = ct.Reactor(contents=LH2)
    LR.volume = 7.0
    
    #Fuel cell reactor
    FCH2 = ct.Hydrogen()
    LH2.TP = 293.0, 2.0 * ct.one_atm
    Rextr = ct.Reservoir(FCH2)
    
    FCVLV = ct.MassFlowController(LR,Rextr,mdot=0.0)
    MassOn = False
    
    #Reactor network for the tank
    network = ct.ReactorNet([LR])
    
    #Time integartion
    t = 0.0
    dt = 1.0
    
    Res = []
    
    Res.append('{:>6s} {:>5s} {:>8s} \n'.format(
            'Time', 'Mass', 'mdot'))
    
    Res.append('{:6.0f} {:5.3f} {:8.6f} \n'.format(
              t, LR.get_state()[0], FCVLV.mdot(t)))
    
    while t < 60.0*60*TotTime:
    
        t += dt
    
        #Initiate the FC mass flow after the dormancy time
        if t>= 60.0*60.0*DormTime and t<= 60.0*60.0*(DormTime+1):
            if not MassOn:
                FCVLV.set_mass_flow_rate(0.005)
                MassOn = True
        else:
            if MassOn:
                FCVLV.set_mass_flow_rate(0.0)
                MassOn = False
            
        network.advance(t)
        
        Res.append('{:6.0f} {:5.3f} {:8.6f} \n'.format(
              t, LR.get_state()[0], FCVLV.mdot(t)))
        
    with open('Results.txt','+w') as fout:
        for lin in Res:
            fout.write(lin)
            
    print('Done')

1. With DormTime = 0.3  and TotTime = 1.5, the mass flow is switched on at 1080 seconds as requested, but the mass in the tank won't reduce until t = 3814, where arbitrarily reduces by 0.002 instead of the 0.005 requested. The mass flow is correctly switched off at t = 4680, but the mass keeps reducing. It eventually switches off at t = 4845 .

2. With DormTime = 5.0 and TotTime = 7.0, the mass flow is switched on and off correctly, but no mass is taken out of the tank at any point.

To me it seems like a bug, but I am not that experienced with cantera and I might have messed something up.

**Comment by bryanwweber** [comment]
Is this a duplicate of this: https://stackoverflow.com/questions/51557332/python-cantera-massflowcontroller-wont-extract-mass-from-reactor

**Comment by skyreflectedinmirrors** [comment]
I believe the issue is that updating the mass flow on the `MassFlowController` w/o resyncing the reactor network doesn't change the mass flow rate in the C++ backend.  A simple fix is:

```
import cantera as ct

#Variables
DormTime = 0.3 #hrs
TotTime = 1.5 #hrs

#Tank Reactor
LH2 = ct.Hydrogen()
LH2.TD = 20.24, 44.623

LR = ct.Reactor(contents=LH2)
LR.volume = 7.0

#Fuel cell reactor
FCH2 = ct.Hydrogen()
LH2.TP = 293.0, 2.0 * ct.one_atm
Rextr = ct.Reservoir(FCH2)

def mdot(t):
    if t>= 60.0*60.0*DormTime and t<= 60.0*60.0*(DormTime+1):
        return 0.005
    return 0

FCVLV = ct.MassFlowController(LR,Rextr,mdot=mdot)
MassOn = False

#Reactor network for the tank
network = ct.ReactorNet([LR])

#Time integartion
t = 0.0
dt = 1.0

Res = []

Res.append('{:>6s} {:>5s} {:>8s} \n'.format(
        'Time', 'Mass', 'mdot'))

Res.append('{:6.0f} {:5.3f} {:8.6f} \n'.format(
          t, LR.get_state()[0], FCVLV.mdot(t)))

while t < 60.0*60*TotTime:

    t += dt
    #Initiate the FC mass flow after the dormancy time
    network.advance(t)

    Res.append('{:6.0f} {:5.3f} {:8.6f} \n'.format(
          t, LR.get_state()[0], FCVLV.mdot(t)))

with open('Results.txt','+w') as fout:
    for lin in Res:
        fout.write(lin)

print('Done')
```

which does decrease the mass of the reactor.  Alternative you'd have to rebuild the reactor network after each switch on/off, as I don't believe there's a method like [syncState](https://cantera.org/documentation/docs-2.3/sphinx/html/cython/zerodim.html#cantera.ReactorBase.syncState) for the MFC.

**Comment by speth** [comment]
You should not call the `set_mass_flow_rate` function or make any other changes to the reactor network once you start integrating. This is because the underlying Sundials integrator can and will take timesteps which end after the time specified in the call to `advance`, and provides results at the specified time by interpolation. Thus, it will not necessarily see your change to the mass flow rate at the expected time.

The method @arghdos shows is the correct way to set a time-dependent mass flow rate.

In addition, since in your system you have nothing to provide a sense of time scale to the integrator except for the time dependent mass flow rate you specified, you probably also want to limit the integrator step size, using the `ReactorNet.set_max_time_step` function.

Finally, I would suggest the Cantera Users' Group would be the better starting place for posting issues such as this, where other users and developers can help diagnose the issue, and then if it seems like a  bug in Cantera, a report filed here would make sense.

**Comment by Repiklis** [comment]
Thank you all for your very quick answers. They really helped to solve my issue. 

I though that this was a bug, because if I am not mistaken (very likely), the [ic_engine.py](https://cantera.org/examples/python/reactors/ic_engine.py.html) example in the documentation is using my initial approach, calling `set_mass_flow_rate` during the integration (lines 137-141). On the other hand, [fuel_injection.py](https://cantera.org/examples/python/reactors/fuel_injection.py.html) is doing it correctly. I think these are the only two examples under Reactor Networks that set the mass flow as a function of time.

 I am sorry for posting this here, but I was not aware of the User's Group (not a very good excuse). I will use it first with future issues. 

This is indeed a (reduced) duplicate of my stackoverflow post, which got no answer after several days, despite using a bounty.
