### ISSUE TITLE
Typo in src/thermo/SpeciesThermoFactory.cpp ?

### ISSUE THREAD

**Issue by decaluwe** [Cantera/cantera#594]
### Cantera version
2.4.0

In `src/thermo/SpeciesThermoFactory.cpp` function `newSpeciesThermoInterpType`, the switch case `CONSTANT_CP`  appears not to return anything (lines 37-38).

Because `const_cp` and `simple` both return `itype` `CONSTANT_CP`, it seems like the case `SIMPLE` on line 38 is actually unnecessary, and instead `case CONSTANT_CP`  should return `new ConstCpPoly(tlow, thigh, pref, coeffs)`

However, this seems like it would be a fairly big error that someone would have run into, so I wanted to raise the issue here, to make sure it is in fact an error, before submitting a PR to fix.  

Thoughts?

**Comment by speth** [comment]
https://github.com/Cantera/cantera/blob/e3424d8ed49f5f7611bc94933109292d32b732ec/src/thermo/SpeciesThermoFactory.cpp#L35-L41

`switch` statements in C/C++ are a little weird -- execution does not stop just because you reach a new `case` label, but keeps going until you reach a `break` or `return` statement. What this means is that for both the `CONSTANT_CP` and `SIMPLE` cases, the code returns a new `ConstCpPoly` object, which is the correct behavior since `SIMPLE` is basically just an alias for `CONSTANT_CP`.

Arguably, the `SIMPLE` type should be deprecated, since it's just a less-descriptive name `CONSTANT_CP`. Ultimately, I'd like to retire all of the integer constants in favor of string names which translate a bit more cleanly across language boundaries.

**Comment by decaluwe** [comment]
Okay, thanks.  I think the `SIMPLE` case should be removed, though.  As noted above, there is no `itype` which is assigned to `SIMPLE`.  On line 59-60 of that file:
```
if (type == "const_cp" || type == "simple") {
        itype = CONSTANT_CP;
```

**Comment by speth** [comment]
I don't think it should be removed without going through the deprecation cycle, because if a user is working in C++, they could be calling the `newSpeciesThermoInterpType(int type, ...)` function directly, rather than the version that uses string names.

**Comment by decaluwe** [comment]
Ah, okay - I was not considering that.  Thanks for the clarification.

SD
