### ISSUE TITLE
save/restore ThermoPhase state assumes density is an independent variable

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#595]
The functions `Phase::saveState` and `Phase::restoreState` assume that temperature and density are the independent thermodynamic variables, which is not true for several of Cantera's thermo models. For these models, the save/restore feature does not work correctly. For example (in Python):
```python
import cantera as ct
phase = ct.ThermoPhase('test_problems/cathermo/issp/IdealSolidSolnPhaseExample.xml')
T0, p0 = phase.TP # T0 = 500, p0 == 101325
z = phase.state # calls Phase::saveState
phase.TP = 600, 2*ct.one_atm
phase.state = z # calls Phase::restoreState
assert phase.T == T0, 'temperature'
assert phase.P == p0, 'pressure'
```
Here, the pressure is left at 2 atm, despite the call to `restoreState`. In other cases, the `restoreState` call will fail because the derived class overrides the `setDensity` function to throw an exception.

Among other things, this error contributes to making these phases difficult to use with the `Solution` class in Python and Matlab, where the default behavior of instantiating a dummy `Transport` object triggers calls to `saveState` and `restoreState`, with the latter failing.

This problem can be resolved by making the `saveState` and `restoreState` methods virtual and having them work with the appropriate set of independent variables for each phase type.

**Comment by ThanasisMattas** [comment]
Hello! I would like to have a look on this issue. I think this could be handled parallel to this @todo entry commented in Phase.h:

  @todo
    - Make the concept of saving state vectors more general, so that it can
      handle other cases where there are additional internal state variables,
      such as the voltage, a potential energy, or a strain field.

 
So, possible overrides at derived classes will use their access methods for every other state variable, like voltage(). So, is just a virtual keyword enough here? And both methods can be overridden at the derived class. More specificly, I would like to ask if this requires any re-implementation of the overridden methods so that they handle the proper state variables (and, corresponding to the todo entry, to add any state variable to the state vector).
