### ISSUE TITLE
Add a function to find species by chemical formula

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#603]
There are a few places in Cantera where a model handles a particular species in a special way, e.g. H<sub>2</sub>O and CO<sub>2</sub> in the [flame radiatiaton model](https://github.com/Cantera/cantera/blob/5ad656e34286efe5e9700a049a6b5a1b1773d06f/src/oneD/StFlow.cpp#L93), and O<sub>2</sub><sup>-</sup> in [IonGasTransport](https://github.com/Cantera/cantera/blob/5ad656e34286efe5e9700a049a6b5a1b1773d06f/src/transport/IonGasTransport.cpp#L196) and we currently do this based on matching the species name. However, there is generally no requirement that species be named in this way, so it would be useful if we could find these species by their atomic composition instead.

This could be done in C++ by adding an overload to `Phase::speciesIndex` which takes a `compositionMap` as the argument. For the Python interface, it could involve another `elif` check for a `dict` containing the composition.

**Comment by seilkhanovk** [comment]
Hey @speth! I am going to work on this issue. However, I have a question. What do you mean by atomic composition? Also, can you provide an example?

**Comment by decaluwe** [comment]
Atomic composition: how many atoms of each species.  e.g. Water is ‘H:2, O:1’  While I might name the species “H2O,” there is no requirement that I do this.  I could just as easily call the species “water,” in which case I would not handle this species in the intended manner.

Examples: I believe Ray provided direct links to two examples in his post - the flame radiation model and IonGasTransport

Best of luck!

**Comment by ThanasisMattas** [comment]
Hello! I took a look on this issue, if that's ok, and I think the overload is correct. Should I make any other changes (for example the input parameters at the examples provided in the discription) or make a pull request with just the overload?

**Comment by bryanwweber** [comment]
I think this issue is sufficiently resolved by #714. The proposed use case here, to identify species by composition for internal uses, can be accomplished by `Phase::findIsomers()`, with a subsequent call to `Phase::speciesIndex()` with the resulting name if necessary.

After a good bit of work in #635, there doesn't appear to be a consistent way to handle species with multiple isomers. There were basically two proposed solutions:
1. Having the function throw/raise if there are isomers. This is not very useful because in most mechanisms of any decent size, there are a good number of species with isomers, so some large fraction of the cases would error out and the user is back at square one
2. Returning a vector of indices. This results in an (IMO) inconsistent interface in Python, where you get a different return type depending on the type of what is passed to the function. In any case, `findIsomers` and the equivalent Python function already return a list of isomers, so a user can use that to find the index of their species of interest.

**Comment by speth** [comment]
Yeah, I agree. I think this turned out to be a massive can of worms, and we're best off leaving things as they are now.
