### ISSUE TITLE
Update to 2018 CODATA physical constants

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#650]
With the release of the new definition of the kilogram, we should update the CODATA physical constants and atomic weights of the elements. This issue serves as a discussion platform for how the constants should be defined.

## Physical constants

The most recent values of the constants can be found from NIST: https://physics.nist.gov/cuu/Constants/Table/allascii.txt

Some of the constants have a defined value, e.g., [Avogadro's Number](https://physics.nist.gov/cgi-bin/cuu/Value?k|search_for=adopted_in!) and the [Boltzmann Constant](https://physics.nist.gov/cgi-bin/cuu/Value?k|search_for=adopted_in!). However, in `ct_defs.h`, the Boltzmann constant is calculated:

https://github.com/Cantera/cantera/blob/ba8ac1d519b12fd19e80d0b05688d720a734664c/include/cantera/base/ct_defs.h#L77

Should we reverse this, so the Gas Constant is calculated from Boltzmann and Avogadro? Leave it as is? Or "overspecify" the values, since the [Gas Constant](https://physics.nist.gov/cgi-bin/cuu/Value?r|search_for=physchem_in!) is also given. I personally prefer the latter approach to avoid differences between platforms/compilers, etc. due to floating point arithmetic (small though the difference may be).

Also, should we add more constants to the list? Are there any others that would be useful to include?

## Atomic masses

There appear to be two sources for atomic masses, the [Standard Atomic Weights](http://www.ciaaw.org/atomic-weights.htm), which include a range of values for some elements depending on the relative isotopic abundance, or the [Current Atomic Masses](http://www.ciaaw.org/atomic-masses.htm). I'm not sure which of these we should use. It is also not clear to me whether or not these values have been adjusted for the new definition of the kilogram. Presumably not, since they were only updated in August 2018 and/or 2017.

**Comment by speth** [comment]
- I think it would be appropriate to define `GasConstant` as `Avogadro * Boltzmann`, and I don't think floating point rounding will be an issue (or at least, it's the same issue whether you do the calculation ahead of time or not).
- I would not add any more constants to this file unless we are already using them elsewhere, and there aren't any of those that I'm aware of.
- We care about atomic weights, not specific isotopic masses, so the first table is the relevant one.
- For those cases where a range is specified (which in includes a lot of the most important ones for Cantera), we of course need a single value. These "conventional" atomic weights are also provided by CIAAW, but for some reason a little harder to find in an authoritative form. The [IUPAC periodic table](https://iupac.org/what-we-do/periodic-table-of-elements/) seems to have them, at least.
- Since the atomic weights are all defined relative to <sup>12</sup>C (specified to be atomic weight 12), these values shouldn't be directly affected by the updates to the physical constants.
- As an aside, the fact that the CODATA update made in 2019 is referred to as the "CODATA 2018 adjustment" is moderately confusing.

**Comment by bryanwweber** [comment]
> As an aside, the fact that the CODATA update made in 2019 is referred to as the "CODATA 2018 adjustment" is moderately confusing.

Yes, I had to check that it was the values published on May 20, 2019. I guess the experiments were conducted last year up through the end of last year.

> The IUPAC periodic table seems to have them, at least.

The precision of those values seems rather lower than the existing values. Do you know where the existing values came from? FWIW, Wikipedia lists all of the values: https://en.wikipedia.org/wiki/Standard_atomic_weight#List_of_atomic_weights
