### ISSUE TITLE
License of file gch.py is GPL-2.0

### ISSUE THREAD

**Issue by OliverFendt** [Cantera/cantera#769]
Dear cantera maintainers

**System information**

- Cantera version: 2.4.0
- OS: Windows 10
- Python/MATLAB version: source code package

In contrast to the license specified in License.txt (which is a BSD-3-Clause customized license) the file cantera-2.4.0/site_scons/site_tools/gch.py is licensed under GPL-2.0.
How is the file used in the context of the entire package? Causes the inclusion of this file the package to be handled as licensed under GPL-2.0?
Are there differences between the Python version and the MATLAB version in regard to that file

**Comment by speth** [comment]
I see, that does introduce a bit of unfortunate confusion.

The `gch.py` file is used as part of the build process for Cantera, to manage generation of a precompiled header. From the perspective of the main Cantera code (including the Python and Matlab interfaces), I don't see this as being any different from using GCC to compile Cantera, which certainly does not require that the software be licensed under the GPL.

I also don't think it's necessary for Cantera's build scripts to be licensed under the same license as the build tools that they use. Otherwise, there would be a conflict between the MIT license used by SCons and the GPL-2.0 license used by that plugin.

The inclusion of that file definitely does not supercede Cantera's BSD 3-clause license, any more than the licenses for vendored dependencies in the `ext` folder do.

**Comment by OliverFendt** [comment]
Thank you very much for the clarification on gch.py.

**Comment by speth** [comment]
If you're satisfied that there's no action needed, can you close this issue?

**Comment by OliverFendt** [comment]
resolved, thank you
