### ISSUE TITLE
Improve the error message when the phases key is missing from a YAML input file

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#812]
As reported on the User's Group (https://groups.google.com/d/msg/cantera-users/2sNq2p-fVKM/-fSXMWA9CAAJ), a YAML input file that is missing a top-level `phases` key has a misleading error message:
```
CanteraError:
***********************************************************************
InputFileError thrown by AnyValue::getMapWhere:
Error on line 1 of /Users/bryan/Downloads/cantera.yaml:
Element is not a mapping or list of mappings
|  Line |
>     1 > species:
          ^
|     2 | - name: H
|     3 |   composition: {H: 1}
|     4 |   thermo:
***********************************************************************
```
It would be nice if this could be improved to point out the actual problem. Minimal YAML file:

```
species:
- name: H
  composition: {H: 1}
  thermo:
    model: NASA7
    temperature-ranges: [200.0, 1000.0, 6000.0]
    data:
    - [2.5, 0.0, 0.0, 0.0, 0.0, 2.547366e+04, -0.44668285]
    - [2.5, 0.0, 0.0, 0.0, 0.0, 2.547366e+04, -0.44668285]
    note: L6/94
```

**Comment by ischoegl** [comment]
@bryanwweber ... I proposed a fix in #880, and found also other instances where the error messages could be misleading (the behavior is caused by cython having incomplete C++ `const` support, with an error-throwing operator being shadowed by a permissive one). ~However, I'm not 100% sure of what 'missing' keywords should be allowed. `nasa.yaml` comes to mind ...~ **Edit:** Nevermind, `argon.yaml` works as expected, so #880 is good.
