### ISSUE TITLE
Compiling Cantera from source fails to find numpy and cython in conda environment

### ISSUE THREAD

**Issue by sevyharris** [Cantera/cantera#963]
**Problem description**
When compiling Cantera from source, scons fails to find the required numpy and cython packages, even though they are installed in the conda environment. I found a solution, which was to add "python_cmd = /path/to/conda/install/folder/envs/bin/python" to the cantera.conf file, but this answer took me several days to come by, and it might be nice to add something about it to the [documentation](https://cantera.org/compiling/installation-reqs.html#sec-installation-reqs).

**Steps to reproduce**

1. Clone Cantera source from github. If it matters, I was working on [this](https://github.com/12Chao/cantera) forked version
2. Created a conda environment with the following command: `conda create --name cantera_from_src python=3.7.9 scons=4.0.1 cython boost numpy ruamel_yaml` and activate with `conda activate cantera_from_src`
3. Edit cantera.conf to produce the full package by adding the lines: `python_package = 'full'` and `boost_inc_dir = '/home/moon/anaconda3/envs/cantera_from_src/include'`
4. Build with `scons build`
5. Install with `sudo scons install`

**Behavior**
The install fails with the following error: <code><pre>ERROR: Unable to build the full Python package because compatible versions of Python, Numpy, and Cython could not be found.
</pre></code>

This mode of failure is confusing because numpy and cython are both installed in the environment. I believe what is happening is that scons is using the wrong python bin. The installation works if I specify the python binary by adding `python_cmd="\home\moon\anaconda3\envs\cantera_from_src\bin\python3.7` to the cantera.conf file.

The main problem was that I had a very hard time figuring that out from the installation instructions. I don't know if there's a way to fix this in the SConstruct file or if we should just add a line to the [compilation requirements](https://cantera.org/compiling/installation-reqs.html#sec-installation-reqs) suggesting people add the python bin to cantera.conf if they run into this issue.

**System information**

- Cantera version: 95473248344b8c4558c71a18ce44b8ab235808c8 found [here](https://github.com/12Chao/cantera)
- OS: Windows Subsystem Linux (Windows 10 and Ubuntu 20.04.1 LTS)
- Python/MATLAB/other software versions:  Python 3.7.9, conda 4.9.2

**Attachments**
Here is the output of `conda list` <code><pre> Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
boost                     1.74.0           py37h6dcda5c_3    conda-forge
boost-cpp                 1.74.0               hc6e9bd1_2    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cython                    0.29.21          py37hcd2ae1e_2    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.19.5           py37haa41c4c_1    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
python                    3.7.9           hffdb5ce_0_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
ruamel_yaml               0.15.80         py37h5e8e339_1003    conda-forge
scons                     4.0.1            py37h89c1867_2    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge</pre></code>

Here is the entirety of the `sudo scons install` result in the terminal <code><pre>(cantera_from_src) moon@LAPTOP-8EPEBLM5:~/cantera_from_source$ sudo scons install
scons: Reading SConscript files ...
INFO: SCons is using the following Python interpreter: /usr/bin/python3
Configuration variables read from 'cantera.conf' and command line:
    python_package = 'full'
    boost_inc_dir = '/home/moon/anaconda3/envs/cantera_from_src/include'

Checking for C++ header file cmath... (cached) yes
Checking for C++ header file fmt/ostream.h... (cached) no
INFO: Using private installation of fmt library.
INFO: Found fmt version 6.2.1
Checking for C++ header file yaml-cpp/yaml.h... (cached) no
INFO: Using private installation of yaml-cpp library.
Checking for C++ header file gtest/gtest.h... (cached) no
Checking for C++ header file gmock/gmock.h... (cached) no
INFO: Using Googletest from Git submodule
Checking for C++ header file Eigen/Dense... (cached) no
INFO: Using private installation of Eigen.
INFO: Found Eigen version 3.3.7
Checking whether __GLIBCXX__ is declared... (cached) yes
Checking whether __clang__ is declared... (cached) no
INFO: Found Boost version 1.74
Checking whether boost::core::demangle is declared... yes
Checking for CVodeCreate(CV_BDF, CV_NEWTON) in C++ library sundials_cvodes... (cached) no
Checking for CVodeCreate(CV_BDF) in C++ library sundials_cvodes... (cached) no
Checking for double x; log(x) in C library None... (cached) no
INFO: Using private installation of Sundials version 5.3.
INFO: Using 'gfortran' to build the Fortran 90 interface
WARNING: Unexpected output while checking Python / Numpy / Cython versions:
| No module named 'numpy'
| No module named 'Cython'
NumPy not found.
Cython not found.
ERROR: Unable to build the full Python package because compatible versions of Python, Numpy, and Cython could not be found.</pre></code>

**Additional context**

**Comment by speth** [comment]
The key here is the use of `sudo` -- I'm guessing that the initial call to `scons build` correctly detects Cython and Numpy? The reason that installing with `sudo` doesn't work is that `sudo` does not transfer environment variables (for good security reasons), so it is not actually running in your Conda environment. You can see this by running `sudo which python`, which will report the path to the system Python interpreter rather than your `conda` one.

I don't think we recommend the use of `sudo` to install Cantera anywhere, and the idea of installing as root but using a Conda environment that belongs to your user is a little confusing. But it might be worth mentioning somewhere in the installation docs that specifying the full path to the conda Python interpreter as `python_cmd` is an alternative to activating the Conda environment.

**Comment by bryanwweber** [comment]
> specifying the full path to the conda Python interpreter as python_cmd is an alternative to activating the Conda environment.

This isn't entirely true. Environments can also set environment variables when they're activated, such as `$LD_LIBRARY_PATH` and so forth. I'd be wary of suggesting this as an alternative.

> I don't think we recommend the use of `sudo` to install Cantera anywhere

I think in at least one place we use the `[sudo] scons install` notation (I think at least in the output after finishing the build), using the manpage arcana of square brackets indicating optional things. People not aware of that might misinterpret or otherwise ignore the brackets. I'm not sure of a better way to specify this, other than to drop the `sudo` entirely, since one probably shouldn't be putting these files into `root`-owned places anyways, unless you already know what you're doing. I'm not sure it would be a reasonable change in the default to put Cantera's files into `~/.local` or something, especially the C++ header files/library.

**Comment by sevyharris** [comment]
I don't remember if I tried `scons install` before `sudo scons install`, but it gives me an error without sudo:

<code><pre>
(cantera_from_src) moon@LAPTOP-8EPEBLM5:~/cantera_from_source$ scons install
scons: Reading SConscript files ...
INFO: SCons is using the following Python interpreter: /home/moon/anaconda3/envs/cantera_from_src/bin/python
Configuration variables read from 'cantera.conf' and command line:
    python_package = 'full'
    boost_inc_dir = '/home/moon/anaconda3/envs/cantera_from_src/include'

Checking for C++ header file cmath... (cached) yes
Checking for C++ header file fmt/ostream.h... (cached) no
INFO: Using private installation of fmt library.
INFO: Found fmt version 6.2.1
Checking for C++ header file yaml-cpp/yaml.h... (cached) no
INFO: Using private installation of yaml-cpp library.
Checking for C++ header file gtest/gtest.h... (cached) no
Checking for C++ header file gmock/gmock.h... (cached) no
INFO: Using Googletest from Git submodule
Checking for C++ header file Eigen/Dense... (cached) no
INFO: Using private installation of Eigen.
INFO: Found Eigen version 3.3.7
Checking whether __GLIBCXX__ is declared... (cached) yes
Checking whether __clang__ is declared... (cached) no
INFO: Found Boost version 1.74
Checking whether boost::core::demangle is declared... (cached) yes
Checking for CVodeCreate(CV_BDF, CV_NEWTON) in C++ library sundials_cvodes... (cached) no
Checking for CVodeCreate(CV_BDF) in C++ library sundials_cvodes... (cached) no
Checking for double x; log(x) in C library None... (cached) no
INFO: Using private installation of Sundials version 5.3.
INFO: Using 'gfortran' to build the Fortran 90 interface
INFO: Using NumPy version 1.19.5.
INFO: Using Cython version 0.29.21.
INFO: Building the full Python package for Python 3.7
scons: done reading SConscript files.
scons: Building targets ...
scons: *** [/usr/local/include/cantera/Edge.h] /usr/local/include/cantera/Edge.h: Permission denied
scons: building terminated because of errors.</pre></code>


I don't know if it's because I already had Cantera installed using a different environment or what. Pure speculation on my part.

**Comment by bryanwweber** [comment]
No, that error is expected without `sudo`. You're trying to write into the `/usr/...` directories which are owned by the `root` user and therefore password protected.

Do you only plan to use the Python interface? In that case, I'd suggest that you change into the `interfaces/cython` directory and run `python setup.py build --build-lib=../../build/python install`. That will only install the Python interface into the current `site-packages` directory of `python`, and you won't need `sudo`, since you're using Anaconda.

**Comment by speth** [comment]
> > I don't think we recommend the use of `sudo` to install Cantera anywhere
> 
> I think in at least one place we use the `[sudo] scons install` notation (I think at least in the output after finishing the build), using the manpage arcana of square brackets indicating optional things.

Yes, you're right. I forgot about that. Removing the mention of `sudo` might be worthwhile.

> I'm not sure it would be a reasonable change in the default to put Cantera's files into `~/.local` or something, especially the C++ header files/library.

Actually, if `$CONDA_PREFIX` is set, and corresponds to the copy of Python the Cantera Python module is being built for, maybe installing everything into that conda environment would be a good default behavior...

Otherwise, I think we need to update some of our installation instructions to let users know that they probably want to build with `scons build prefix=$CONDA_PREFIX` if they are using Conda. That  beats running the Python module installation manually.

**Comment by bryanwweber** [comment]
I think this is fixed by the combination of #974, Cantera/enhancements#75, and Cantera/enhancements#76.
